# examples/flutter-macos-simple-example.yml
# 開発用シンプルビルド

name: Flutter macOS Simple Build

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    uses: tomoya-cicd/github-actions-workflows/.github/workflows/flutter-cicd.yml@main
    with:
      flutter-version: '3.24.0'
      target-platforms: 'macos'
      build-mode: 'release'
      runs-on: 'self-hosted'
