# iOS Native CI/CD 使用例
# Swift/SwiftUI、UIKit を使ったネイティブiOSアプリ向け

name: iOS CI/CD Example

on:
  push:
    branches: [main, develop]
    tags:
      - 'v*'
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  ios-build:
    uses: tomoya-cicd/github-actions-workflows/.github/workflows/ios-cicd.yml@main
    
    with:
      # Xcode設定
      xcode-version: '15.2'
      xcode-project: 'MyApp.xcodeproj'
      scheme: 'MyApp'
      configuration: 'Release'
      
      # テスト設定
      run-tests: true
      simulator: 'iPhone 15 Pro'
      ios-version: '17.2'
      
      # デプロイ設定（mainブランチまたはタグの場合）
      deploy-testflight: ${{ github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v') }}
      
      # ランナー（Mac Studio使用時はself-hosted）
      runs-on: 'macos-14'  # または 'self-hosted'
    
    secrets:
      # Apple Developer証明書
      APPLE_CERTIFICATE_BASE64: ${{ secrets.APPLE_CERTIFICATE_BASE64 }}
      APPLE_CERTIFICATE_PASSWORD: ${{ secrets.APPLE_CERTIFICATE_PASSWORD }}
      APPLE_PROVISIONING_PROFILE_BASE64: ${{ secrets.APPLE_PROVISIONING_PROFILE_BASE64 }}
      KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
      
      # App Store Connect API
      APPLE_API_KEY_ID: ${{ secrets.APPLE_API_KEY_ID }}
      APPLE_API_ISSUER_ID: ${{ secrets.APPLE_API_ISSUER_ID }}
      APPLE_API_KEY_BASE64: ${{ secrets.APPLE_API_KEY_BASE64 }}
